# Generated by Django 5.2.7 on 2025-10-23 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)])),
                ('altura', models.IntegerField(help_text='Altura en centímetros', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(300)])),
                ('imc', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de Masa Corporal', max_digits=5, null=True)),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=20)),
                ('objetivo', models.CharField(choices=[('perdida_peso', 'Pérdida de peso'), ('recomposicion', 'Recomposición genética'), ('hipertrofia', 'Hipertrofia')], max_length=20)),
                ('porcentaje_grasa', models.DecimalField(decimal_places=1, help_text='Porcentaje de grasa corporal', max_digits=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(60)])),
                ('tiempo_entrenamiento', models.IntegerField(help_text='Tiempo promedio de entrenamiento por sesión en minutos', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(230)])),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
