# Generated by Django 5.2.7 on 2025-10-23 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='porcentaje_grasa',
            field=models.DecimalField(decimal_places=1, help_text='Porcentaje de grasa corporal', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tiempo_entrenamiento',
            field=models.IntegerField(blank=True, help_text='Tiempo promedio de entrenamiento por sesión en minutos', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(230)]),
        ),
    ]
