# Generated by Django 5.2.7 on 2025-10-29 21:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE_App', '0002_alter_userprofile_porcentaje_grasa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], help_text='Día de la semana')),
                ('nombre_dia', models.CharField(help_text='Ej: Pecho y Tríceps', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Notas adicionales del día', null=True)),
            ],
            options={
                'verbose_name': 'Día de Entrenamiento',
                'verbose_name_plural': 'Días de Entrenamiento',
                'ordering': ['plan', 'numero_dia'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Técnica y consejos', null=True)),
                ('tipo_equipo', models.CharField(choices=[('mancuerna', 'Mancuerna'), ('barra', 'Barra'), ('polea', 'Polea'), ('maquina', 'Máquina'), ('peso_corporal', 'Peso Corporal'), ('banda_elastica', 'Banda Elástica'), ('kettlebell', 'Kettlebell')], max_length=20)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', max_length=15)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['grupo_muscular', 'nombre_ejercicio'],
            },
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(help_text='Ej: Pecho, Espalda, Piernas', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo Muscular',
                'verbose_name_plural': 'Grupos Musculares',
                'ordering': ['nombre_grupo'],
            },
        ),
        migrations.CreateModel(
            name='DiaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='Posición en la rutina del día')),
                ('series', models.IntegerField(help_text='Número de series', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('repeticiones', models.CharField(help_text='Ej: 8-12, 15, 20+', max_length=20)),
                ('peso_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Peso sugerido en kg', max_digits=5, null=True)),
                ('descanso_minutos', models.DecimalField(decimal_places=1, help_text='Descanso entre series en minutos', max_digits=3)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_asignados', to='FE_App.diaentrenamiento')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_asignados', to='FE_App.ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio del Día',
                'verbose_name_plural': 'Ejercicios del Día',
                'ordering': ['dia', 'orden'],
                'unique_together': {('dia', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='FE_App.grupomuscular'),
        ),
        migrations.CreateModel(
            name='HistorialEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('serie_num', models.IntegerField(help_text='Número de serie realizada', validators=[django.core.validators.MinValueValidator(1)])),
                ('repeticiones_realizadas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_utilizado', models.DecimalField(decimal_places=2, help_text='Peso utilizado en kg', max_digits=5)),
                ('rpe', models.IntegerField(help_text='Rate of Perceived Exertion (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('molestia_nivel', models.IntegerField(default=0, help_text='Nivel de molestia/dolor (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales', null=True)),
                ('dia_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='FE_App.diaejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_entrenamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Entrenamiento',
                'verbose_name_plural': 'Historiales de Entrenamiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(help_text='Ej: Plan Hipertrofia 12 semanas', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo', models.CharField(help_text='Objetivo del plan', max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('pausado', 'Pausado')], default='activo', max_length=15)),
                ('dias_semana', models.IntegerField(default=4, help_text='Días de entrenamiento por semana', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('riesgo_lesion', models.BooleanField(default=False, help_text='Predicción ML: Riesgo de lesión')),
                ('riesgo_estancamiento', models.BooleanField(default=False, help_text='Predicción ML: Riesgo de estancamiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_entrenamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Entrenamiento',
                'verbose_name_plural': 'Planes de Entrenamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='diaentrenamiento',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='FE_App.planentrenamiento'),
        ),
        migrations.AlterUniqueTogether(
            name='diaentrenamiento',
            unique_together={('plan', 'numero_dia')},
        ),
    ]
