# Generated by Django 5.2.7 on 2025-11-11 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE_App', '0003_diaentrenamiento_ejercicio_grupomuscular_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def normalize_active_plans(apps, schema_editor):
        Plan = apps.get_model('FE_App', 'PlanEntrenamiento')
        # Por cada usuario con más de un plan activo, mantener el más reciente y pausar el resto
        user_ids = (Plan.objects
                    .filter(estado='activo')
                    .values_list('usuario_id', flat=True)
                    .distinct())
        for uid in user_ids:
            activos = (Plan.objects
                       .filter(usuario_id=uid, estado='activo')
                       .order_by('-fecha_actualizacion', '-id'))
            keep = activos.first()
            if keep:
                activos.exclude(id=keep.id).update(estado='pausado')

    operations = [
        migrations.AlterField(
            model_name='planentrenamiento',
            name='nombre_plan',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(normalize_active_plans, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='planentrenamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('usuario',), name='unique_active_plan_per_user'),
        ),
    ]
